version: '3.7'

services:
  db_master:
    image: bitnami/postgresql:16.1.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repluser
      - POSTGRESQL_REPLICATION_PASSWORD=replpassword
    volumes:
      - ./db/backup:/backup
      - ./db/sync/config:/config
      - ./db/sync/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5

  rabbit:
    image: rabbitmq:3.13.0-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword

  db_slave_1:
    image: bitnami/postgresql:16.1.0
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRESQL_MASTER_HOST=db_master
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repluser
      - POSTGRESQL_REPLICATION_PASSWORD=replpassword
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_CLUSTER_APP_NAME=db_slave_1
    depends_on:
      db_master:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5

  db_slave_2:
    image: bitnami/postgresql:16.1.0
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRESQL_MASTER_HOST=db_master
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repluser
      - POSTGRESQL_REPLICATION_PASSWORD=replpassword
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - POSTGRESQL_CLUSTER_APP_NAME=db_slave_2
    depends_on:
      db_master:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 2s
      retries: 5

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      GUNICORN_ACCESS_LOGFILE: /dev/null
    ports:
      - "5050:80"
    links:
      - db_master
    logging:
      driver: none

  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379

  backend:
    build:
      args:
        JAR_FILE: build/libs/socialnetwork-1.0.jar
    ports:
      - "8080:8080"
    depends_on:
      db_master:
        condition: service_healthy
      db_slave_1:
        condition: service_healthy
      db_slave_2:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-master:5432/sn
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - RABBIT_HOST=rabbit
      - RABBIT_PORT=5672
      - RABBIT_USERNAME=rmuser
      - RABBIT_PASSWORD=rmpassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379