###
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "email": "imfromkazan@yandex.ru",
  "firstName": "Ivan",
  "secondName": "Ivanov",
  "gender": 1,
  "birthDate": "1986-05-10",
  "city": "Kazan",
  "password": "qwerty",
  "interests": [
    "swimming",
    "crafting",
    "science"
  ],
  "isCelebrity": false
}

###
POST http://localhost:8080/user/login
Content-Type: application/json

{
  "email": "imfromkazan@yandex.ru",
  "password": "qwerty"
}
> {% client.global.set("auth_token", response.body.token) %}

###
POST http://localhost:8080/user/info
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": "4846a879-2cc9-44d4-966b-db49dbe3ecec"
}

###
POST http://localhost:8080/user/search
Content-Type: application/json

{
  "firstName": "А",
  "lastName": "А"
}


###
POST http://localhost:8080/friend/add
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "friendId": "4846a879-2cc9-44d4-966b-db49dbe3ecec"
}

###
POST http://localhost:8080/feed/get
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "forceUpdate": false
}

